[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}
{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
tag_pattern = "^mcp-v[0-9].*"
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^test", group = "Tests" },
  { message = "^docs\\(changelog\\)", skip = true },
  { message = "^ci\\(changelog\\)", skip = true },
  { message = "^ci", group = "CI" },
  { message = "^build", group = "Build" },
  { message = "^docs", group = "Docs" },
  { message = "^refactor", group = "Refactors" },
  { message = "^chore\\(deps\\)", group = "Dependencies" },
  { message = "^chore", group = "Chores" },
  { message = "^revert", group = "Reverts" },
]
