#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);

/** Resolves this workspace's own pinned `wrangler` binary via Node's module resolution (walking up
 *  from this file's node_modules tree), never PATH. `execFileSync("wrangler", ...)` would silently
 *  fall through to PATH -- and pick up a globally-installed wrangler with a DIFFERENT bundled workerd
 *  version, with zero warning -- whenever node_modules/.bin/wrangler doesn't exist yet (a fresh clone
 *  or worktree before `npm ci` has run). require.resolve has no such fallback: it throws immediately
 *  and loudly if the local package isn't installed, instead of silently generating wrong output.
 *  wrangler's own package.json restricts its `exports` map, so the bin subpath itself isn't directly
 *  requireable -- resolve the package root via its (always-exported) package.json instead, then read
 *  the real bin path from there rather than hand-hardcoding "./bin/wrangler.js". */
export function resolveLocalWranglerBin(): string {
  const pkgJsonPath = require.resolve("wrangler/package.json");
  const pkg: { bin: string | Record<string, string> } = JSON.parse(readFileSync(pkgJsonPath, "utf8"));
  const binRelativePath = typeof pkg.bin === "string" ? pkg.bin : pkg.bin.wrangler!;
  return join(dirname(pkgJsonPath), binRelativePath);
}

// Cloudflare's own `wrangler types` output packs every declared env var into ONE long single-line
// `Pick<Cloudflare.Env, "A" | "B" | ...>>` union (the generated ProcessEnv interface). Two independent PRs
// that each add a DIFFERENT new var to wrangler.jsonc's `vars` regenerate that SAME line with their own
// insertion -- git's line-based 3-way merge sees "the same line changed differently in both branches" and
// reports a conflict on worker-configuration.d.ts, even though the two additions are logically unrelated
// (hit repeatedly across the #1667 incident-followup PRs). This wrapper still regenerates via the real
// `wrangler types` CLI (so it can never drift from wrangler's own output), then reformats JUST that one
// union onto one sorted entry per line -- two PRs adding different vars now land on different, non-adjacent
// lines and merge cleanly like every other interface body in this file already does.
export const OUTPUT_PATH = "worker-configuration.d.ts";
const TEMP_PATH = ".worker-configuration.gen-check.d.ts";
const PICK_RE = /Pick<Cloudflare\.Env, ((?:"[^"]+" \| )*"[^"]+")>>/;

/** Pure: strip trailing whitespace (wrangler's own raw output convention this repo has always normalized),
 *  normalize wrangler's own "Generated by ... running `wrangler types [path]`" header comment (it echoes
 *  whatever path argument was passed, which check mode intentionally sets to a different temp path than
 *  the real OUTPUT_PATH — without this, check mode would always report false staleness on that line alone),
 *  then reformat the single-line ProcessEnv Pick<Cloudflare.Env, ...> union into one sorted entry per line. */
export function formatCfTypegenOutput(source: string): string {
  const stripped = source.replace(/[ \t]+$/gm, "").replace(/(Generated by Wrangler by running `wrangler types)[^`]*`/, "$1`");
  const match = stripped.match(PICK_RE);
  if (!match) {
    throw new Error(`Could not find the ProcessEnv Pick<Cloudflare.Env, ...> union in the generated output to reformat.`);
  }
  const keys = match[1]!
    .split(" | ")
    .map((quoted) => quoted.slice(1, -1))
    .sort((a, b) => a.localeCompare(b));
  const lines = keys.map((key) => `\t\t| "${key}"`).join("\n");
  return stripped.replace(PICK_RE, `Pick<Cloudflare.Env,\n${lines}\n\t>>`);
}

export function genCfTypegen({ check = false } = {}): { changed: boolean | undefined } {
  const target = check ? TEMP_PATH : OUTPUT_PATH;
  try {
    execFileSync(process.execPath, [resolveLocalWranglerBin(), "types", target], { stdio: "inherit" });
    const generated = formatCfTypegenOutput(readFileSync(target, "utf8"));
    if (!check) {
      writeFileSync(OUTPUT_PATH, generated);
      return { changed: undefined };
    }
    const current = readFileSync(OUTPUT_PATH, "utf8");
    return { changed: current !== generated };
  } finally {
    if (check && existsSync(TEMP_PATH)) unlinkSync(TEMP_PATH);
  }
}

function main(argv: string[]) {
  const check = argv.includes("--check");
  const { changed } = genCfTypegen({ check });
  if (check) {
    if (changed) {
      process.stderr.write(`gen-cf-typegen: ${OUTPUT_PATH} is stale; run npm run cf-typegen.\n`);
      process.exit(1);
    }
    process.stdout.write(`gen-cf-typegen: ${OUTPUT_PATH} is up to date.\n`);
    return;
  }
  process.stdout.write(`gen-cf-typegen: wrote ${OUTPUT_PATH}.\n`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main(process.argv.slice(2));
}
