import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { formatCfTypegenOutput, resolveLocalWranglerBin } from "../../scripts/gen-cf-typegen.js";

// #1667-followup: wrangler's own `wrangler types` output packs every declared env var into ONE long
// single-line `Pick<Cloudflare.Env, "A" | "B" | ...>>` union. Two independent PRs that each add a DIFFERENT
// new var regenerate that SAME line with their own insertion -- git's line-based 3-way merge sees "the same
// line changed differently in both branches" and reports a real merge conflict on worker-configuration.d.ts,
// even though the two additions are logically unrelated. This hit several same-day PRs in a row. The fix:
// reformat that one union onto one sorted entry per line, so two independent additions land on different,
// non-adjacent lines and merge cleanly like every other interface body in this file already does.
function rawFixture(vars: string[]): string {
  const union = vars.map((v) => `"${v}"`).join(" | ");
  return [
    "/* eslint-disable */",
    "// Generated by Wrangler by running `wrangler types` (hash: deadbeef)",
    "// Runtime types generated with workerd@1.0.0 2026-01-01 nodejs_compat",
    "interface Env {}",
    "declare namespace NodeJS {",
    `\tinterface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, ${union}>> {}`,
    "}",
    "",
  ].join("\n");
}

describe("gen-cf-typegen: formatCfTypegenOutput", () => {
  it("reformats the single-line Pick<Cloudflare.Env, ...> union into one sorted entry per line", () => {
    const out = formatCfTypegenOutput(rawFixture(["ZEBRA", "ALPHA", "MID"]));
    expect(out).toContain('Pick<Cloudflare.Env,\n\t\t| "ALPHA"\n\t\t| "MID"\n\t\t| "ZEBRA"\n\t>>');
  });

  it("sorts regardless of the original declaration order", () => {
    const outAsc = formatCfTypegenOutput(rawFixture(["A", "B", "C"]));
    const outDesc = formatCfTypegenOutput(rawFixture(["C", "B", "A"]));
    expect(outAsc).toBe(outDesc);
  });

  it("normalizes the wrangler header's echoed path argument so a different invocation path does not read as a content change", () => {
    const bare = formatCfTypegenOutput(rawFixture(["A"]));
    const withPath = formatCfTypegenOutput(rawFixture(["A"]).replace("wrangler types` (hash", "wrangler types .some-temp-path.d.ts` (hash"));
    expect(bare).toBe(withPath);
  });

  it("strips trailing whitespace from every line", () => {
    const withTrailingWhitespace = rawFixture(["A"]).replace("interface Env {}", "interface Env {}   ");
    const out = formatCfTypegenOutput(withTrailingWhitespace);
    expect(out).not.toMatch(/ +\n/);
    expect(out).toContain("interface Env {}\n");
  });

  it("throws when the ProcessEnv Pick<Cloudflare.Env, ...> union is not found", () => {
    expect(() => formatCfTypegenOutput("interface Env {}\n")).toThrow(/Could not find the ProcessEnv/);
  });

  // A stale global `wrangler` install can silently generate types from the WRONG (mismatched) workerd
  // version with zero warning if resolution falls through to PATH. resolveLocalWranglerBin uses Node's
  // own require.resolve instead of a bare "wrangler" execFileSync call, so it can only ever find this
  // workspace's own pinned dependency -- never a same-named binary elsewhere on the machine.
  it("resolveLocalWranglerBin resolves this workspace's own pinned wrangler binary, not PATH", () => {
    const resolved = resolveLocalWranglerBin();
    expect(resolved).toContain(join("node_modules", "wrangler", "bin", "wrangler.js"));
    expect(existsSync(resolved)).toBe(true);
  });

  it("REGRESSION: two independent single-var additions no longer conflict under a real git 3-way merge", () => {
    const dir = mkdtempSync(join(tmpdir(), "cf-typegen-merge-"));
    try {
      const base = formatCfTypegenOutput(rawFixture(["ALPHA", "MID", "ZEBRA"]));
      const ours = formatCfTypegenOutput(rawFixture(["ALPHA", "BRAVO", "MID", "ZEBRA"])); // adds BRAVO
      const theirs = formatCfTypegenOutput(rawFixture(["ALPHA", "MID", "YANKEE", "ZEBRA"])); // adds YANKEE
      const basePath = join(dir, "base.d.ts");
      const oursPath = join(dir, "ours.d.ts");
      const theirsPath = join(dir, "theirs.d.ts");
      writeFileSync(basePath, base);
      writeFileSync(oursPath, ours);
      writeFileSync(theirsPath, theirs);

      const merged = execFileSync("git", ["merge-file", "-p", oursPath, basePath, theirsPath], { encoding: "utf8" });
      expect(merged).not.toContain("<<<<<<<");
      expect(merged).toContain('| "BRAVO"');
      expect(merged).toContain('| "YANKEE"');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("BASELINE: the SAME two additions DO conflict on the original unformatted single-line union", () => {
    const dir = mkdtempSync(join(tmpdir(), "cf-typegen-merge-baseline-"));
    try {
      const base = rawFixture(["ALPHA", "MID", "ZEBRA"]);
      const ours = rawFixture(["ALPHA", "BRAVO", "MID", "ZEBRA"]);
      const theirs = rawFixture(["ALPHA", "MID", "YANKEE", "ZEBRA"]);
      const basePath = join(dir, "base.d.ts");
      const oursPath = join(dir, "ours.d.ts");
      const theirsPath = join(dir, "theirs.d.ts");
      writeFileSync(basePath, base);
      writeFileSync(oursPath, ours);
      writeFileSync(theirsPath, theirs);

      let conflicted = false;
      let merged = "";
      try {
        merged = execFileSync("git", ["merge-file", "-p", oursPath, basePath, theirsPath], { encoding: "utf8" });
      } catch (error) {
        conflicted = true;
        merged = String((error as { stdout?: string }).stdout ?? "");
      }
      expect(conflicted).toBe(true);
      expect(merged).toContain("<<<<<<<");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
