// Generated by scripts/gen-command-reference.ts. Do not edit manually.
// Regenerate via `npm run command-reference`.
export const PUBLIC_COMMAND_ENTRIES = [
  {
    id: "help",
    title: "LoopOver command help",
    description: "Show public-safe @loopover command help.",
  },
  {
    id: "ask",
    title: "LoopOver contribution context Q&A",
    description:
      "Answer contribution-quality questions from connected cached sources with citations.",
  },
  {
    id: "chat",
    title: "LoopOver grounded chat Q&A",
    description:
      "Answer a question in natural prose from cached decision-pack facts via local Ollama (maintainer/collaborator; read-only).",
  },
  {
    id: "preflight",
    title: "LoopOver preflight",
    description: "Summarize public PR hygiene and validation readiness.",
  },
  {
    id: "blockers",
    title: "LoopOver readiness blockers",
    description: "Explain public-safe readiness blockers.",
  },
  {
    id: "duplicate-check",
    title: "LoopOver duplicate & WIP check",
    description: "Summarize duplicate and in-progress overlap caution.",
  },
  {
    id: "miner-context",
    title: "LoopOver miner context",
    description: "Confirm public Gittensor miner context when available.",
  },
  {
    id: "next-action",
    title: "LoopOver next step",
    description: "Suggest the next public-safe action.",
  },
  {
    id: "reviewability",
    title: "LoopOver PR readiness",
    description: "Summarize maintainer-friendly PR readiness without private review internals.",
  },
  {
    id: "repo-fit",
    title: "LoopOver repository fit",
    description: "Summarize public-safe repository fit signals.",
  },
  {
    id: "packet",
    title: "LoopOver public packet",
    description: "Prepare public-safe PR packet guidance.",
  },
] as const;

export const PUBLIC_COMMAND_LIST =
  "@loopover help\n@loopover ask\n@loopover chat\n@loopover preflight\n@loopover blockers\n@loopover duplicate-check\n@loopover miner-context\n@loopover next-action\n@loopover reviewability\n@loopover repo-fit\n@loopover packet";

export const MAINTAINER_COMMAND_ENTRIES = [
  {
    id: "queue-summary",
    title: "LoopOver maintainer queue summary",
    description: "Post a maintainer-only queue digest from cached GitHub metadata.",
  },
  {
    id: "confirmed-miners",
    title: "LoopOver confirmed-miner PRs",
    description: "List open PRs whose authors are confirmed in the official-miner cache.",
  },
  {
    id: "review-now",
    title: "LoopOver review-now queue",
    description: "List cached PRs that look ready for maintainer review.",
  },
  {
    id: "needs-author",
    title: "LoopOver needs-author queue",
    description: "List cached PRs that need author cleanup before detailed review.",
  },
  {
    id: "duplicate-clusters",
    title: "LoopOver duplicate clusters",
    description: "List duplicate or WIP clusters visible from cached GitHub metadata.",
  },
  {
    id: "burden-forecast",
    title: "LoopOver burden forecast",
    description: "Project maintainer review load and queue-growth risk from cached metadata.",
  },
  {
    id: "intake-health",
    title: "LoopOver intake health",
    description: "Summarize contributor-intake health from cached queue and config signals.",
  },
  {
    id: "outcome-patterns",
    title: "LoopOver outcome patterns",
    description: "Summarize what this repo actually merges vs closes from cached PR outcomes.",
  },
  {
    id: "noise-report",
    title: "LoopOver noise report",
    description: "Highlight queue noise sources maintainers should triage first.",
  },
] as const;

export const MAINTAINER_COMMAND_LIST =
  "@loopover queue-summary\n@loopover confirmed-miners\n@loopover review-now\n@loopover needs-author\n@loopover duplicate-clusters\n@loopover burden-forecast\n@loopover intake-health\n@loopover outcome-patterns\n@loopover noise-report";

export const ACTION_COMMAND_ENTRIES = [
  {
    id: "gate-override",
    title: "Gate override",
    description:
      "Record a maintainer override for this commit's gate check only (does not persist across new commits).",
  },
  {
    id: "review",
    title: "Request review",
    description:
      "Request an auto-review run on the current PR head (`@loopover re-review` is an alias).",
  },
  {
    id: "pause",
    title: "Pause auto-review",
    description:
      "Pause auto-review for this PR with an optional reason; does not change gate enforcement.",
  },
  {
    id: "resume",
    title: "Resume auto-review",
    description:
      "Resume auto-review for this PR with an optional reason; does not change gate enforcement.",
  },
  {
    id: "resolve",
    title: "Resolve finding",
    description:
      "Mark a review finding as resolved, optionally naming the finding in trailing text.",
  },
  {
    id: "configuration",
    title: "Show configuration",
    description: "Show the effective resolved review configuration for this repository.",
  },
  {
    id: "explain",
    title: "Explain finding",
    description:
      "Explain a specific review finding; supply the finding reference in trailing text.",
  },
  {
    id: "generate-tests",
    title: "Generate E2E tests",
    description:
      "Generate an AI E2E test for this PR's changed behavior and post it as a reply comment (maintainer-only).",
  },
] as const;

export const ACTION_COMMAND_LIST =
  "@loopover gate-override\n@loopover review\n@loopover pause\n@loopover resume\n@loopover resolve\n@loopover configuration\n@loopover explain\n@loopover generate-tests";
